[theme] 
primaryColor="gainsboro"
backgroundColor= "darkslateblue"       
secondaryBackgroundColor="darkorange"
textColor="#ffffff"
font="sans serif"

# darkslateblue color can also be used as background color and looks quite good or darkorange #1D6